# Generated by Django 5.1.2 on 2026-05-14 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('qty', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('notional', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('order_type', models.CharField(default='market', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('filled', 'Filled'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('filled_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('filled_avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('alpaca_order_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
